//! The report: tables, graphs, rankings, and what the run did NOT establish.
//!
//!  THE REPORT OPENS WITH WHAT IT COULD NOT SHOW. Not in an appendix, not
//! after the recommendation - first, where a reader skimming for the answer
//! cannot miss it. Failed cells, unsupported configurations, noisy
//! measurements and missing controls come before any ranking.

use crate::model::*;
use crate::rank::{self, Row};
use crate::svg;
use crate::validate::{Finding, Severity};
use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

fn f3(v: Option<f64>) -> String {
    match v {
        //  A dash where the value is unknown. Never a zero, never a blank
        // that could be read as one.
        None => "–".into(),
        Some(x) if !x.is_finite() => "–".into(),
        Some(x) => format!("{:.3}", x),
    }
}
fn pct(v: Option<f64>) -> String {
    match v {
        None => "–".into(),
        Some(x) if !x.is_finite() => "–".into(),
        Some(x) => format!("{:.1}%", x * 100.0),
    }
}
fn mib(v: Option<u64>) -> String {
    match v {
        None => "–".into(),
        Some(b) => format!("{:.2}", b as f64 / (1024.0 * 1024.0)),
    }
}

/// A ratio column, as a reader acts on it: the exact ratio, then what it means.
///
///  `0.595×` is precise and `40.5% faster` is legible, and the table now
/// carries both rather than making every reader do the subtraction.  Where the
/// row's distance from the control is inside its own MAD the cell says
/// `≈ control` instead of a percentage - printing "4.8% faster" for a lead
/// smaller than a 6.4% spread is the exact claim `docs/AGENTS.md` §9 forbids,
/// and run D of the `mechanisms` suite is the case that forced the rule.
fn rel_cell(
    rel: Option<f64>,
    rel_mad: Option<f64>,
    is_baseline: bool,
    better: &str,
    worse: &str,
) -> String {
    match rel {
        None => "–".into(),
        Some(x) if !x.is_finite() => "–".into(),
        Some(x) if is_baseline => format!("{:.3}× *(control)*", x),
        Some(x) if svg::tie_with_control(x, rel_mad) => {
            format!("{:.3}×  ≈ control", x)
        }
        Some(x) => format!("{:.3}× ({})", x, svg::rel_phrase(x, better, worse)),
    }
}

pub struct Report {
    pub markdown: String,
    pub charts: BTreeMap<String, String>,
    pub rankings_json: String,
}

pub fn build(
    meta: &RunMeta,
    plan: &[Cell],
    results: &[CellResult],
    findings: &[Finding],
    workload: &str,
) -> Report {
    let mut m = String::new();
    let groups = rank::build_rows(results, workload);
    let verdicts = rank::verdicts(&groups);

    let ok = results.iter().filter(|r| r.rankable()).count();
    let unsupported: Vec<&CellResult> = results
        .iter()
        .filter(|r| r.outcome == "unsupported")
        .collect();
    let failed: Vec<&CellResult> = results
        .iter()
        .filter(|r| r.outcome != "ok" && r.outcome != "unsupported")
        .collect();

    // ---------------------------------------------------------------- header
    let _ = writeln!(m, "# Allocator benchmark - run `{}`\n", meta.run_id);
    let _ = writeln!(
        m,
        "Generated by `alloc-bench report`.  Do not edit: it is overwritten from the dataset in `results/`.\n"
    );

    // ------------------------------------------- what this run did NOT show
    let _ = writeln!(m, "## What this run does not establish\n");
    let _ = writeln!(
        m,
        "Read this before the tables. It is not a disclaimer; it is the list of \
         questions these numbers cannot answer.\n"
    );
    let _ = writeln!(m, "| | |");
    let _ = writeln!(m, "| --- | --- |");
    let _ = writeln!(
        m,
        "| **one machine, one day** | `{}`, {} × `{}`, {} MiB RAM, kernel `{}`. Absolute timings here do not transfer to other hardware. Ratios within a group are the transferable part, and even those are measured, not guaranteed. |",
        meta.host.cpu_model,
        meta.host.cpu_count,
        meta.host.arch,
        meta.host.mem_total_kb / 1024,
        meta.host.kernel
    );
    let _ = writeln!(
        m,
        "| **cells that could not exist** | {} configuration(s) are unsupported, each with a recorded technical reason. They are listed below rather than dropped. |",
        unsupported.len()
    );
    let _ = writeln!(
        m,
        "| **cells that failed** | {} configuration(s) were attempted and did not produce a usable result. Also listed below. |",
        failed.len()
    );
    if meta.host.emulated {
        let _ = writeln!(
            m,
            "|  **emulated** | the target architecture is not the host's, so this ran under binfmt emulation. Timings are recorded and **excluded from ranking**: emulation changes the instruction mix and the memory behaviour, so the comparison would measure the emulator. |"
        );
    }
    let noisy: Vec<&Finding> = findings.iter().filter(|f| f.check == "noisy").collect();
    if !noisy.is_empty() {
        let _ = writeln!(
            m,
            "| **noise** | {} cell(s) measured a relative MAD above the {:.0}% threshold. Differences smaller than that cell's own spread are not attributable to the allocator. |",
            noisy.len(),
            crate::validate::NOISE_REL_MAD_WARN * 100.0
        );
    }
    let _ = writeln!(
        m,
        "| **what an allocator is good at generally** | this measures one application (ripgrep) on one corpus shape. ripgrep is not allocation-bound; an allocation-heavy service would rank differently, and nothing here says otherwise. |"
    );
    let _ = writeln!(
        m,
        "| **security** | hardened_malloc trades performance for memory-safety mitigations. A slower row for it is the expected cost of what it does, not a defect, and this project makes no claim about whether those mitigations work. |\n"
    );

    // ------------------------------------------------------------ conditions
    let _ = writeln!(m, "## Conditions\n");
    let _ = writeln!(m, "| | |");
    let _ = writeln!(m, "| --- | --- |");
    let _ = writeln!(m, "| run id | `{}` |", meta.run_id);
    let _ = writeln!(m, "| started | {} |", meta.started_at);
    let _ = writeln!(m, "| suites | {} |", meta.suites.join(", "));
    let _ = writeln!(m, "| repository commit | `{}` |", meta.git_commit);
    let _ = writeln!(m, "| corpus seed | `{}` |", meta.corpus_seed);
    let _ = writeln!(
        m,
        "| container runtime | {} {} |",
        meta.host.container_runtime, meta.host.runtime_version
    );
    let _ = writeln!(m, "| primary workload | `{}` |", workload);
    let env = &meta.host.env;
    let mut prop = |label: &str, key: &str, value: Option<String>| {
        let cell = match value {
            Some(v) => v,
            None => match env.unread.get(key) {
                Some(why) => format!("– *(not readable: {})*", why),
                // Unreachable while `host_env` files a reason for every empty
                // field, and said out loud rather than printed as a dash: a
                // silent blank here is the failure the `unread` map exists for.
                None => "– *(not probed)*".to_string(),
            },
        };
        let _ = writeln!(m, "| {} | {} |", label, cell);
    };
    prop(
        "page size",
        "page_size_bytes",
        env.page_size_bytes.map(|v| format!("{} bytes", v)),
    );
    prop(
        "transparent huge pages",
        "transparent_hugepage",
        env.transparent_hugepage.clone().map(|v| format!("`{}`", v)),
    );
    prop(
        "CPU caches",
        "cpu_caches",
        env.cpu_caches.clone().map(|v| format!("`{}`", v)),
    );
    prop(
        "NUMA nodes",
        "numa_nodes",
        env.numa_nodes.map(|v| v.to_string()),
    );
    prop(
        "threads per core",
        "threads_per_core",
        env.threads_per_core.map(|v| v.to_string()),
    );
    prop(
        "CPU governor",
        "scaling_governor",
        env.scaling_governor.clone().map(|v| format!("`{}`", v)),
    );
    prop(
        "CPUs the orchestrator was allowed",
        "cpus_allowed",
        env.cpus_allowed.clone().map(|v| format!("`{}`", v)),
    );
    for (k, v) in &meta.ci {
        let _ = writeln!(m, "| {} | `{}` |", k, v);
    }
    let _ = writeln!(m);

    // ------------------------------------------------------- pinned versions
    let _ = writeln!(m, "### Exactly what produced these numbers\n");
    let _ = writeln!(m, "| component | ref | commit |");
    let _ = writeln!(m, "| --- | --- | --- |");
    for (id, e) in &meta.lock.entries {
        let _ = writeln!(
            m,
            "| `{}` | {} `{}` | [`{}`]({}/commit/{}) |",
            id,
            e.kind,
            e.reference,
            &e.commit[..e.commit.len().min(12)],
            e.repo,
            e.commit
        );
    }
    let _ = writeln!(m);

    // --------------------------------------------------------------- results
    let _ = writeln!(m, "## Rankings\n");
    let _ = writeln!(
        m,
        " **Every ordering below is a statement about one machine - {} ({} core(s)), \
         `{}`.** The same six cells have produced three different orderings on three CPUs, \
         and the run that inverted the result reported the *tightest* spread of the three. \
         Never quote a row from this table without naming this machine; \
         `results/rolling/` is where a claim about more than one lives.\n",
        meta.host.cpu_model, meta.host.cpu_count, meta.host.kernel
    );
    let _ = writeln!(
        m,
        "Ordered by median execution time on `{}`, fastest first. `rel` is the ratio against \
         the control in the SAME image, architecture, profile and toolchain - no ratio crosses a group. \
         `MAD` is the relative median absolute deviation of that cell's own samples: **a difference \
         smaller than the MAD is not a result**.\n",
        workload
    );

    let _ = writeln!(
        m,
        "**How to read it.** Every measured column is one where \
         **{}**, marked `↓` in the header: less time, less memory, a smaller \
         binary and a tighter spread are all the good direction. A `rel` under \
         `1.000×` beat the control and one over it lost.\n",
        svg::direction_note(svg::Better::Lower)
    );
    let _ = writeln!(
        m,
        "| marker | meaning |\n| --- | --- |\n\
         | `↓` in a header | lower is better for this column |\n\
         | `≈ control` |  this row's distance from the control is **smaller than its own MAD**, so this run does not establish that it is faster or slower. §9's rule, applied per row. |\n\
         | `–` | not measured.  Never a zero, and never a blank that could be read as one. |\n"
    );
    let _ = writeln!(
        m,
        "Composite, where shown: `{}` - also **lower is better**, and every \
         component is published separately so a reader who weighs them \
         differently can re-rank.\n",
        rank::COMPOSITE_FORMULA
    );

    let mut charts: BTreeMap<String, String> = BTreeMap::new();

    for (g, rows) in &groups {
        let _ = writeln!(m, "### {}\n", g);
        let _ = writeln!(
            m,
            "| # | allocator | mechanism | time (s) ↓ | vs control ↓ | MAD ↓ | peak RSS (MiB) ↓ | vs control ↓ | size (MiB) ↓ | startup (s) ↓ | composite ↓ |"
        );
        let _ = writeln!(
            m,
            "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"
        );
        for (i, r) in rows.iter().enumerate() {
            let _ = writeln!(
                m,
                "| {} | {}{} | `{}` | {} | {} | {} | {} | {} | {} | {} | {} |",
                i + 1,
                variant_label(r),
                if r.is_baseline { " *(control)*" } else { "" },
                r.integration,
                f3(r.time_s),
                rel_cell(r.rel_time, r.rel_mad, r.is_baseline, "faster", "slower"),
                pct(r.rel_mad),
                f3(r.rss_kb.map(|v| v / 1024.0)),
                rel_cell(r.rel_rss, None, r.is_baseline, "less", "more"),
                mib(r.size_bytes),
                f3(r.startup_s),
                f3(r.composite),
            );
        }
        let _ = writeln!(m);

        if let Some(v) = verdicts.iter().find(|v| &v.group == g) {
            if v.within_noise {
                let _ = writeln!(m, ">  **No winner is claimed here.** {}\n", v.note);
            } else {
                let _ = writeln!(
                    m,
                    "> **Fastest: {}.** {}\n",
                    v.winner.clone().unwrap_or_else(|| "–".into()),
                    v.note
                );
            }
        }

        let slug = g.replace([' ', '/'], "").replace("--", "-");
        if let Some(c) = svg::relative_time_chart(g, rows, workload) {
            charts.insert(format!("time-{}.svg", slug), c);
            let _ = writeln!(m, "![relative time](time-{}.svg)\n", slug);
        }
        if let Some(c) = svg::relative_rss_chart(g, rows, workload) {
            charts.insert(format!("rss-{}.svg", slug), c);
            let _ = writeln!(m, "![relative peak RSS](rss-{}.svg)\n", slug);
        }
        if let Some(c) = svg::size_chart(g, rows) {
            charts.insert(format!("size-{}.svg", slug), c);
            let _ = writeln!(m, "![binary size](size-{}.svg)\n", slug);
        }
    }

    // ------------------------------------------------------- per-libc answer
    //
    //  THE QUESTION A READER ARRIVES WITH, answered where they will see it:
    // "which allocator on musl, which on glibc". No per-group table answers it,
    // because a group is one distribution.
    let libc_rows = rank::by_libc(&groups);
    if libc_rows.iter().any(|s| s.distros.len() > 1) {
        let _ = writeln!(m, "## Which allocator, by libc\n");
        let _ = writeln!(
            m,
            "Each candidate against **its own distribution's control**, counted \
             across every distribution of that libc in this run.  No ratio crosses \
             a distribution; what is counted is how many distributions it won in.\n"
        );
        let _ = writeln!(
            m,
            " **A win means the lead exceeded that cell's own MAD.** Anything smaller \
             is counted as a **tie**, never rounded into a win - {}. A cell with no \
             MAD at all counts as a tie, because nothing can be said about whether its \
             difference cleared the noise.\n",
            svg::direction_note(svg::Better::Lower)
        );
        for s in &libc_rows {
            let _ = writeln!(
                m,
                "### {} - {} distribution(s): {}\n",
                s.libc,
                s.distros.len(),
                s.distros
                    .iter()
                    .map(|d| format!("`{}`", d))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            if s.distros.len() < 2 {
                let _ = writeln!(
                    m,
                    " **One distribution.** Nothing here is a statement about {} - it is \
                     a statement about `{}`.\n",
                    s.libc,
                    s.distros.first().map(String::as_str).unwrap_or("?")
                );
            }
            let _ = writeln!(
                m,
                "| allocator | mechanism | beat its control in | lost in | tied in | median ↓ | range ↓ | peak RSS range ↓ |"
            );
            let _ = writeln!(m, "| --- | --- | --- | --- | --- | --- | --- | --- |");
            for r in &s.rows {
                let names = |v: &Vec<String>| {
                    if v.is_empty() {
                        "–".to_string()
                    } else {
                        format!("**{}** ({})", v.len(), v.join(", "))
                    }
                };
                let _ = writeln!(
                    m,
                    "| {} | `{}` | {} | {} | {} | {:.3}× | {:.3}–{:.3}× | {} |",
                    r.allocator,
                    r.integration,
                    names(&r.wins),
                    names(&r.losses),
                    names(&r.ties),
                    r.rel_median,
                    r.rel_min,
                    r.rel_max,
                    match (r.rss_min, r.rss_max) {
                        (Some(a), Some(b)) if (b - a).abs() < 1e-9 => format!("{:.3}×", a),
                        (Some(a), Some(b)) => format!("{:.3}–{:.3}×", a, b),
                        _ => "–".into(),
                    }
                );
            }
            let _ = writeln!(m);

            let n = s.distros.len();

            //  A ROW THAT SAW FEWER DISTRIBUTIONS THAN THE HEADING SAYS IS
            // AMBIGUOUS. "beat its control in 2" under a 3-distribution heading
            // reads as "lost one" when it may mean "never ran there". The
            // difference is named rather than left to arithmetic on the other
            // two columns.
            let partial: Vec<&rank::LibcRow> =
                s.rows.iter().filter(|r| r.distros_seen() < n).collect();
            if !partial.is_empty() {
                let _ = writeln!(
                    m,
                    " **Measured in fewer than all {} distributions**, so their counts \
                     below are out of a smaller number and are not comparable with the \
                     rest: {}. A cell that could not be built is listed under \
                     \"Configurations that failed\" with the reason.\n",
                    n,
                    partial
                        .iter()
                        .map(|r| format!("**{}** ({} of {})", r.allocator, r.distros_seen(), n))
                        .collect::<Vec<_>>()
                        .join(", ")
                );
            }

            let clean: Vec<&rank::LibcRow> = s
                .rows
                .iter()
                .filter(|r| r.wins.len() == n && r.distros_seen() == n)
                .collect();
            if clean.is_empty() {
                let _ = writeln!(
                    m,
                    ">  **No allocator beat the control in every {} distribution here.** \
                     Anything this run recommends would be a recommendation for one \
                     distribution, not for {}.\n",
                    s.libc, s.libc
                );
            } else {
                let best = clean[0];
                // Plain text: the sentences below add the emphasis, and nesting
                // `**` inside `**` renders as literal asterisks.
                let who = clean
                    .iter()
                    .map(|r| r.allocator.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let rss = match (best.rss_min, best.rss_max) {
                    (Some(a), Some(b)) if (b - a).abs() < 1e-9 => format!("{:.3}×", a),
                    (Some(a), Some(b)) => format!("{:.3}–{:.3}×", a, b),
                    _ => "an unrecorded multiple of".into(),
                };
                //  A one-distribution group gets no libc-level verdict. Saying
                // "beat the control in all 1 of them" reads like a sweep and is a
                // statement about one image.
                if n < 2 {
                    let _ = writeln!(
                        m,
                        ">  **{}** beat the control on `{}`. The fastest of them, \
                         **{}**, by a median of {:.3}× (range {:.3}–{:.3}×), costing {} \
                         the control's peak RSS.  This is not a {} result: one \
                         distribution cannot separate the libc from the distribution.\n",
                        who,
                        s.distros.first().map(String::as_str).unwrap_or("?"),
                        best.allocator,
                        best.rel_median,
                        best.rel_min,
                        best.rel_max,
                        rss,
                        s.libc
                    );
                } else {
                    let _ = writeln!(
                        m,
                        ">  **{}** beat the control in **all {} {} distributions**. The \
                         fastest of them, **{}**, by a median of {:.3}× (range \
                         {:.3}–{:.3}×), costing {} the control's peak RSS.  One run on \
                         one machine: a ranking is a property of the machine, so read \
                         this as \"it held on every distribution measured HERE\".{}\n",
                        who,
                        n,
                        s.libc,
                        best.allocator,
                        best.rel_median,
                        best.rel_min,
                        best.rel_max,
                        rss,
                        if clean.len() > 1 {
                            " The ordering between them is not established unless each lead also clears its own MAD."
                        } else {
                            ""
                        }
                    );
                }
            }
        }
    }

    // ------------------------------------------------------ every workload
    let _ = writeln!(m, "## Every workload\n");
    let _ = writeln!(
        m,
        "The ranking above uses one workload. These are all of them, as median seconds, \
         so a reader can see whether the ordering holds or whether it is an artefact of one shape of work.\n"
    );
    let mut workloads: Vec<String> = results
        .iter()
        .flat_map(|r| r.measurements.keys().cloned())
        .collect::<std::collections::BTreeSet<_>>()
        .into_iter()
        .collect();
    workloads.sort();
    if !workloads.is_empty() {
        let _ = writeln!(m, "| cell | {} |", workloads.join(" | "));
        let _ = writeln!(m, "| --- |{}", " --- |".repeat(workloads.len()));
        for r in results.iter().filter(|r| r.rankable()) {
            let cells: Vec<String> = workloads.iter().map(|w| f3(r.median_wall(w))).collect();
            let _ = writeln!(m, "| `{}` | {} |", r.cell.id, cells.join(" | "));
        }
        let _ = writeln!(m);
    }

    // ------------------------------------------------------------- ASLR
    let aslr_rows: Vec<&CellResult> = results
        .iter()
        .filter(|r| r.rankable() && r.aslr.is_some())
        .collect();
    if !aslr_rows.is_empty() {
        let _ = writeln!(m, "## Address-space randomisation, observed\n");
        let _ = writeln!(
            m,
            "Read from `/proc/<pid>/maps` while each binary was running, not inferred from the ELF type. \
             A static non-PIE executable is loaded at a fixed address; a static PIE is not.\n"
        );
        //  THE DIRECTION FLIPS HERE, which is the whole reason the report
        // states it rather than assuming a house convention. Everywhere above,
        // lower is better; in this column a *higher* count of distinct load
        // addresses is the good outcome, and `1 of 6` - the best-looking number
        // on the page if you read it as a ratio - means no randomisation at all.
        let _ = writeln!(
            m,
            " **In this table {}**, unlike every table above it: `6 of 6` distinct load addresses is \
             randomisation working, and `1 of 6` is a binary that lands at the same address every time.\n",
            svg::direction_note(svg::Better::Higher)
        );
        let _ = writeln!(
            m,
            "| cell | profile | link kind | distinct load addresses ↑ | randomised |"
        );
        let _ = writeln!(m, "| --- | --- | --- | --- | --- |");
        for r in aslr_rows {
            let a = r.aslr.as_ref().unwrap();
            let kind = r
                .identity
                .as_ref()
                .and_then(|v| v.get("link_kind"))
                .and_then(|v| v.as_str())
                .unwrap_or("–");
            let _ = writeln!(
                m,
                "| `{}` | {} | {} | {} of {} | {} |",
                r.cell.id,
                r.cell.profile,
                kind,
                a.get("distinct_bases")
                    .and_then(|v| v.as_u64())
                    .unwrap_or(0),
                a.get("sampled").and_then(|v| v.as_u64()).unwrap_or(0),
                a.get("randomised")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false)
            );
        }
        let _ = writeln!(m);
    }

    // ------------------------------------------------------------- preload
    //
    //  Printed for the same reason the ASLR table is: a claim the report makes
    // about a cell should be readable beside the cell's number rather than
    // buried in a JSON file. For a preload cell it is THE identity claim --
    // nothing in the binary says which allocator ran -- so it does not get to be
    // implicit.
    let preload_rows: Vec<&CellResult> = results
        .iter()
        .filter(|r| r.rankable() && r.preload.is_some())
        .collect();
    if !preload_rows.is_empty() {
        let _ = writeln!(m, "## Preloaded libraries, observed resident\n");
        let _ = writeln!(
            m,
            " A preload cell's allocator is **not in its binary**, so the ELF oracle that identifies \
             every other mechanism has nothing to read. These rows are read from `/proc/<pid>/maps` \
             of the running subject: mapped with `LD_PRELOAD` set, and absent without it. \
              The empty control is what makes the positive mean anything.\n"
        );
        //  And here the two columns want OPPOSITE directions, which no single
        // "lower is better" note could carry. The left column must be full and
        // the right one must be empty; a run where both are full has not
        // established anything, because the library was resident with or
        // without the mechanism under test.
        let _ = writeln!(
            m,
            " **The two columns are read in opposite directions.** For `mapped with LD_PRELOAD`, \
             {} - every sample should find the library. For `mapped without`, **lower is better** \
             and the only passing value is **0**.\n",
            svg::direction_note(svg::Better::Higher)
        );
        let _ = writeln!(
            m,
            "| cell | allocator | mapped with LD_PRELOAD ↑ | mapped without (control) ↓ |"
        );
        let _ = writeln!(m, "| --- | --- | --- | --- |");
        for r in preload_rows {
            let p = r.preload.as_ref().unwrap();
            let n = |k: &str, f: &str| {
                p.get(k)
                    .and_then(|v| v.get(f))
                    .and_then(|v| v.as_u64())
                    .map(|v| v.to_string())
                    .unwrap_or_else(|| "–".into())
            };
            let _ = writeln!(
                m,
                "| `{}` | {} | {} of {} sampled | {} of {} sampled |",
                r.cell.id,
                r.cell.allocator,
                n("with_preload", "library_resident"),
                n("with_preload", "subject_sampled"),
                n("without_preload", "library_resident"),
                n("without_preload", "subject_sampled"),
            );
        }
        let _ = writeln!(m);
    }

    // ------------------------------------------------- unsupported and failed
    let _ = writeln!(m, "## Configurations that could not exist\n");
    if unsupported.is_empty() {
        let _ = writeln!(m, "None in this run.\n");
    } else {
        let _ = writeln!(
            m,
            " These are results. Each names a concrete technical reason, and a future upstream \
             release that removes the reason turns the row into a measurement without anyone editing prose.\n"
        );
        let _ = writeln!(m, "| cell | reason |");
        let _ = writeln!(m, "| --- | --- |");
        for r in &unsupported {
            let _ = writeln!(
                m,
                "| `{}` | {} |",
                r.cell.id,
                r.detail
                    .as_deref()
                    .unwrap_or(" no reason recorded - this is itself a defect")
                    .replace('\n', " ")
            );
        }
        let _ = writeln!(m);
    }

    let _ = writeln!(m, "## Configurations that failed\n");
    if failed.is_empty() {
        let _ = writeln!(m, "None in this run.\n");
    } else {
        let _ = writeln!(m, "| cell | outcome | detail |");
        let _ = writeln!(m, "| --- | --- | --- |");
        for r in &failed {
            let _ = writeln!(
                m,
                "| `{}` | `{}` | {} |",
                r.cell.id,
                r.outcome,
                r.detail
                    .as_deref()
                    .unwrap_or("no detail recorded")
                    .replace('\n', " ")
                    .chars()
                    .take(400)
                    .collect::<String>()
            );
        }
        let _ = writeln!(m);
    }

    // ------------------------------------------------------------ validation
    let _ = writeln!(m, "## Validation\n");
    let _ = writeln!(
        m,
        "`alloc-bench validate` checks the dataset before this report is written. \
         An `ERROR` means the ranking above must not be trusted; the exit status reflects it.\n"
    );
    let _ = writeln!(m, "| severity | check | cell | message |");
    let _ = writeln!(m, "| --- | --- | --- | --- |");
    if findings.is_empty() {
        let _ = writeln!(m, "| info | all | – | every check passed |");
    }
    for f in findings {
        let _ = writeln!(
            m,
            "| {} | `{}` | {} | {} |",
            f.severity.as_str(),
            f.check,
            f.cell
                .as_deref()
                .map(|c| format!("`{}`", c))
                .unwrap_or_else(|| "–".into()),
            f.message
                .replace('\n', " ")
                .chars()
                .take(400)
                .collect::<String>()
        );
    }
    let _ = writeln!(m);

    let _ = writeln!(
        m,
        "---\n\n{} cell(s) planned, {} produced a usable result, {} unsupported, {} failed.\n",
        plan.len(),
        ok,
        unsupported.len(),
        failed.len()
    );
    let _ = writeln!(
        m,
        "Raw samples, build metadata, identity evidence and correctness output for every cell are in \
         `results/` and `cells/` beside this file.  Every number above is derived from them; none was typed in."
    );

    let rankings_json = serde_json::to_string_pretty(&serde_json::json!({
        "run_id": meta.run_id,
        "primary_workload": workload,
        "composite_formula": rank::COMPOSITE_FORMULA,
        "groups": groups.iter().map(|(g, rows)| {
            serde_json::json!({
                "group": g,
                "rows": rows.iter().map(row_json).collect::<Vec<_>>(),
            })
        }).collect::<Vec<_>>(),
        "verdicts": verdicts.iter().map(|v| serde_json::json!({
            "group": v.group,
            "winner": v.winner,
            "margin_pct": v.margin_pct,
            "within_noise": v.within_noise,
            "note": v.note,
        })).collect::<Vec<_>>(),
        "findings": findings.iter().map(|f| serde_json::json!({
            "severity": f.severity.as_str(),
            "check": f.check,
            "cell": f.cell,
            "message": f.message,
        })).collect::<Vec<_>>(),
    }))
    .unwrap_or_else(|_| "{}".into());

    Report {
        markdown: m,
        charts,
        rankings_json,
    }
}

/// How an allocator is named in a table row.
///
///  A non-default variant MUST reach the label. Two variants of one
/// allocator share a group -- same distro, arch, profile and toolchain -- so
/// without this the table prints `hardened_malloc` twice with different
/// numbers and the reader cannot tell which is which. The default variant is
/// left unadorned so every existing report renders byte-identically.
fn variant_label(r: &Row) -> String {
    if r.variant == DEFAULT_VARIANT {
        r.allocator.clone()
    } else {
        format!("{} `{}`", r.allocator, r.variant)
    }
}

fn row_json(r: &Row) -> serde_json::Value {
    serde_json::json!({
        "cell_id": r.cell_id,
        "distro": r.distro,
        "arch": r.arch,
        "allocator": r.allocator,
        "variant": r.variant,
        "integration": r.integration,
        "profile": r.profile,
        "toolchain": r.toolchain,
        "time_s": r.time_s,
        "rel_time": r.rel_time,
        "rel_mad": r.rel_mad,
        "rss_kb": r.rss_kb,
        "rel_rss": r.rel_rss,
        "size_bytes": r.size_bytes,
        "rel_size": r.rel_size,
        "startup_s": r.startup_s,
        "composite": r.composite,
        "is_baseline": r.is_baseline,
    })
}

pub fn write(dir: &Path, r: &Report) -> Result<(), String> {
    std::fs::create_dir_all(dir).map_err(|e| format!("{}: {}", dir.display(), e))?;
    std::fs::write(dir.join("report.md"), &r.markdown).map_err(|e| e.to_string())?;
    std::fs::write(dir.join("rankings.json"), &r.rankings_json).map_err(|e| e.to_string())?;
    for (name, svg) in &r.charts {
        std::fs::write(dir.join(name), svg).map_err(|e| format!("{}: {}", name, e))?;
    }
    Ok(())
}

pub fn severity_summary(findings: &[Finding]) -> (usize, usize) {
    (
        findings
            .iter()
            .filter(|f| f.severity == Severity::Error)
            .count(),
        findings
            .iter()
            .filter(|f| f.severity == Severity::Warn)
            .count(),
    )
}
